logging:
  level:
    com:
      jp: warn
    # org:
    #   springframework:
    #     web: info
    # security: DEBUG
    root: warn
  pattern:
    console: "%d{dd-MM HH:mm} - %-5level - %logger{1} - %msg%n"

server:
  port: "8081"

version:
  number: 0.3

jwt:
  secret: mysecretKey4433210

spring:
  jpa:
    open-in-view: "false"
  profiles:
    active: "dev"

---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    username: temp
    password: temp
    url: "jdbc:mysql://localhost:3306/qrcode"
    Driver: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
---
spring:
  main:
    banner-mode: "off"
  config:
    activate:
      on-profile: prod
  datasource:
    username: temp
    password: temp
    url: "jdbc:mysql://localhost:3306/qrcode"
    Driver: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
